tsdf_server:
  ros__parameters:
    world_frame: map
    sensor_frame: unilidar_lidar
    color_map_method: grayscale # [grayscale, rainbow] If the point cloud does not have color value, the color is calculated with its intensity.
                                # If the point cloud does not have intensity also, the color takes constant value.  
    sensor_type: lidar # [lidar]
    layer_publish_hz: 1.0 #

    # map
    tsdf_voxel_size: 0.1
    tsdf_voxels_per_side: 8
    # integrator
    truncation_distance: 0.1
    voxel_carving_enabled: true
    max_ray_length_m: 5.0
    min_ray_length_m: 0.1
    max_weight: 1000.0
    use_const_weight: True # If this takes false, the longer the distance from sensor, the smaller the weight is. 
    use_weight_dropoff: False
    allow_clear: False # If it takes False, only voxels of neighbors of a point are updated
    start_voxel_subsampling_factor: 2.0 # only used for fast integrator (not implemented)
    max_consecutive_ray_collisions: 2 # only used for fast integrator (not implemented)
    clear_checks_every_n_frames: 1 # only used for fast integratior (not implemented)

    # max_integration_time_s: 
    anti_grazing: true # If it take True, the merge integrator update voxel just once. 
                        # If takes False, the voxel value updation is repeated for the number of points in the voxel. 
    use_sparsity_compensation_factor: False # If it takes true, the weight calculated with a point whose the norm of distance form the boundary is smaller than truncation distance 
                                            # is multiplied by "sparsity_compensation_factor". 
    sparsity_compensation_factor: 3.0
    integration_order_mode: "merge" # [simple, merge] simple method uses whole points. Merge method bundles the points before the updation. 
    integrator_threads: 4
    merge_with_clear: true
    weight_reduction_exp: 1.0 # the larget is, the smaller the init weight is. 
    weight_dropoff_epsilon: 0.1 # weight drops until its value becomes under the this value. 
    normal_available: true 
    reliable_band_ratio: 1.0 # point that its distance form boundary is smaller than (truncation_distance*reliable_band_ratio) is considered thier normal. 
    reliable_normal_ratio_thre: 0.1 # point that the angle between its ray and normal is smaller than this value is used for updation. 
    max_ray_through_step_num: 30 # If there is a voxel that it does not reflect no ray, but at least one ray through it while consecutive <max_ray_through_step_num> times, then, voxel weight is cleared.
    use_weight_clear: False # 

    #　sensor
    sensor_image_width: 640
    sensor_image_height: 320
    point_cloud_min_depth: 0.15
    point_cloud_min_z: -0.5
    depth_smooth_thres_ratios: 0.05
    point_cloud_is_loop: true
    min_yaw_fov_rad: -3.14
    yaw_fov_rad_range: 6.28
    min_pitch_fov_rad: 0.0
    pitch_fov_rad_range: 1.57

    # mesh
    mesh_publish_hz: 1.0
    mesh_color_mode: height # [color, height, normals, gray]
    mesh_min_weight: 0.01 # (0.0, 1.0) the voxel whose probability is smaller than this value is ignored. 
    mesh_use_color: true